apiVersion: v1
kind: ReplicationController  # 副本控制器RC
metadata:
  name: mysql  # RC的名称，全局唯一
spec:
  replicas: 1   # Pod副本的期待数量
  selector:
    app: mysql  # 符合目标的pod拥有此标签,===1此处应当一致
  template:     # 根据此模板创建pod的副本
    metadata:
      labels:
        app: mysql  # pod副本拥有的标签,===1此处应当一致
    spec:
      containers:        # pod中容器的定义部分
      - name: mysql   # 容器名称
        image: mysql  # 容器对应的docker镜像
        ports:
          - containerPort: 3306   # 容器应用监听的端口号
        env:                      # 注入容器内的环境变量
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"

