apiVersion: v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000 # 超过一亿被系统保留，给系统组件使用
globalDefault: false
description: "description priority"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
  replicas: 1
  selector:
    app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: tomcat  
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      priorityClassName: high-priority